/**
 * Compute BGE-M3 embeddings for the fixture corpus and write them
 * to `fixture-embedded.ts`.  Run this once after adding new fixture
 * articles, then commit the result.
 *
 * Usage:
 *   OPENROUTER_API_KEY=… npx tsx scripts/embed-fixture.ts
 *
 * Re-running the script overwrites the existing embedded fixture.
 * Articles with the same (title, content) hash will be skipped (cached
 * embeddings).
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { FIXTURE_CORPUS } from '../src/lib/eval/fixture';
import { embed, articleToEmbedText } from '../src/lib/ai/gateway';

async function main() {
  console.log(`[embed-fixture] Embedding ${FIXTURE_CORPUS.length} fixture articles…`);
  const t0 = Date.now();

  const inputs = FIXTURE_CORPUS.map((a) => articleToEmbedText(a.title, a.content));
  const vectors = await embed(inputs);

  console.log(`[embed-fixture] Done in ${Date.now() - t0}ms.`);

  // Serialise the corpus with the vectors baked in.
  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * @module eval/fixture-embedded');
  lines.push(' * @description The fixture corpus with BGE-M3 embeddings');
  lines.push(' * baked in.  Generated by `scripts/embed-fixture.ts`.');
  lines.push(' *');
  lines.push(' * Do NOT edit by hand — re-run the script after adding');
  lines.push(' * articles to `fixture.ts`.');
  lines.push(' *');
  lines.push(' * @author Amadou — Dicken AI');
  lines.push(' * @version auto-generated');
  lines.push(' */');
  lines.push('');
  lines.push("import type { Article } from '@/lib/discover/types';");
  lines.push('');
  lines.push('export const FIXTURE_CORPUS_EMBEDDED: Article[] = [');
  for (let i = 0; i < FIXTURE_CORPUS.length; i++) {
    const a = FIXTURE_CORPUS[i];
    const v = vectors[i];
    lines.push('  {');
    lines.push(`    id: ${JSON.stringify(a.id)},`);
    lines.push(`    topic: ${JSON.stringify(a.topic)},`);
    lines.push(`    title: ${JSON.stringify(a.title)},`);
    lines.push(`    content: ${JSON.stringify(a.content)},`);
    lines.push(`    url: ${JSON.stringify(a.url)},`);
    lines.push(`    thumbnail: null,`);
    lines.push(`    domain: ${JSON.stringify(a.domain)},`);
    lines.push(`    language: ${JSON.stringify(a.language)},`);
    lines.push(`    publishedAt: new Date(${JSON.stringify(a.publishedAt?.toISOString() ?? null)}),`);
    lines.push('    author: null,');
    lines.push(`    qualityScore: ${a.qualityScore},`);
    lines.push(`    createdAt: new Date(${JSON.stringify(a.createdAt.toISOString())}),`);
    lines.push(`    embedding: ${JSON.stringify(v)},`);
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');

  const out = resolve('src/lib/eval/fixture-embedded.ts');
  writeFileSync(out, lines.join('\n'), 'utf-8');
  console.log(`[embed-fixture] Wrote ${out}`);
}

main().catch((err) => {
  console.error('[embed-fixture] failed:', err);
  process.exit(1);
});
